"""🛠️ BoostAPI CLI — scaffold and manage BoostAPI projects."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

import click

# ── Templates bundled with the package ────────────────────────────────────────
TEMPLATES_DIR = Path(__file__).parent / "templates"

# ── Colours ───────────────────────────────────────────────────────────────────
SUCCESS = "green"
INFO = "cyan"
WARN = "yellow"
ERR = "red"


@click.group()
@click.version_option(package_name="boostapi")
def main() -> None:
    """🛠️  BoostAPI — Production FastAPI starter toolkit."""


# ─────────────────────────────────────────────────────────────────────────────
# quickstart
# ─────────────────────────────────────────────────────────────────────────────
@main.command()
@click.argument("project_name")
@click.option("--skip-docker", is_flag=True, help="Skip docker-compose generation")
def quickstart(project_name: str, skip_docker: bool) -> None:
    """
    Scaffold a complete BoostAPI project in <PROJECT_NAME>/.

    \b
    Example:
        boostapi quickstart my-app
        cd my-app
        docker compose up -d
        alembic upgrade head
        uvicorn app.main:app --reload
    """
    project_path = Path(project_name)

    if project_path.exists():
        click.secho(f"⚠️  Directory '{project_name}' already exists.", fg=WARN)
        if not click.confirm("Continue anyway?", default=False):
            sys.exit(1)

    click.secho(f"\n🚀  Creating BoostAPI project: {project_name}", fg=INFO, bold=True)
    project_path.mkdir(parents=True, exist_ok=True)

    # ── App skeleton ──────────────────────────────────────────
    _write_file(
        project_path / "app" / "main.py",
        _MAIN_PY_TEMPLATE.format(project_name=project_name),
    )
    _write_file(project_path / "app" / "__init__.py", "")
    _write_file(project_path / "requirements.txt", _REQUIREMENTS)

    # ── Config ────────────────────────────────────────────────
    _write_file(project_path / ".env", _ENV_TEMPLATE)

    # ── Docker ────────────────────────────────────────────────
    if not skip_docker:
        _copy_or_write(project_path / "docker-compose.yml", _DOCKER_COMPOSE)

    # ── Alembic ───────────────────────────────────────────────
    _write_file(project_path / "alembic.ini", _ALEMBIC_INI.format(project_name=project_name))
    (project_path / "migrations" / "versions").mkdir(parents=True, exist_ok=True)
    _write_file(project_path / "migrations" / "env.py", _ALEMBIC_ENV)

    # ── README ────────────────────────────────────────────────
    _write_file(
        project_path / "README.md",
        f"# {project_name}\n\nGenerated by [BoostAPI](https://pypi.org/project/boostapi/).\n",
    )

    click.echo("")
    click.secho("✅  Project created successfully!\n", fg=SUCCESS, bold=True)
    click.secho("Next steps:", fg=INFO)
    click.echo(f"  cd {project_name}")
    if not skip_docker:
        click.echo("  docker compose up -d          # Start PostgreSQL + Redis")
    click.echo("  alembic upgrade head          # Run migrations")
    click.echo("  uvicorn app.main:app --reload  # Start the API server")
    click.echo("\n  📖  Docs: http://localhost:8000/docs\n")


# ─────────────────────────────────────────────────────────────────────────────
# info
# ─────────────────────────────────────────────────────────────────────────────
@main.command()
def info() -> None:
    """Display BoostAPI version and environment info."""
    from boostapi import __version__

    click.secho(f"\n🛠️  BoostAPI v{__version__}", fg=INFO, bold=True)
    click.echo(f"   Python : {sys.version}")
    click.echo(f"   Path   : {Path(__file__).parent}\n")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    click.secho(f"  📄  {path}", fg="blue")


def _copy_or_write(dest: Path, content: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    click.secho(f"  📄  {dest}", fg="blue")


# ─────────────────────────────────────────────────────────────────────────────
# Embedded templates
# ─────────────────────────────────────────────────────────────────────────────
_MAIN_PY_TEMPLATE = '''\
"""Entry point for {project_name}."""
from boostapi import create_app

app = create_app()
'''

_REQUIREMENTS = """\
boostapi>=0.1.0
uvicorn[standard]>=0.30.0
"""

_ENV_TEMPLATE = """\
POSTGRES_SERVER=localhost
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
POSTGRES_DB=boostapi
REDIS_URL=redis://localhost:6379
SECRET_KEY=change-me-in-production
"""

_DOCKER_COMPOSE = """\
version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: boostapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
volumes:
  postgres_data:
"""

_ALEMBIC_INI = """\
[alembic]
script_location = migrations
sqlalchemy.url = %(DATABASE_URL)s
[loggers]
keys = root,sqlalchemy,alembic
[logger_root]
level = WARN
handlers = console
[logger_sqlalchemy]
level = WARN
handlers =
[logger_alembic]
level = INFO
handlers =
[handlers]
keys = console
[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic
[formatters]
keys = generic
[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
"""

_ALEMBIC_ENV = """\
import asyncio
from logging.config import fileConfig
from alembic import context
from sqlalchemy.ext.asyncio import create_async_engine
from boostapi.app.core.config import settings
from boostapi.app.db.database import Base
from boostapi.app.db import models  # noqa: F401 – register models

config = context.config
fileConfig(config.config_file_name)
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(url=settings.DATABASE_URL, target_metadata=target_metadata,
                      literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    engine = create_async_engine(settings.DATABASE_URL)
    async with engine.connect() as conn:
        await conn.run_sync(lambda c: context.configure(
            connection=c, target_metadata=target_metadata))
        async with conn.begin():
            await conn.run_sync(lambda _: context.run_migrations())
    await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
"""
